// Code generated by the Encore 1.50.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly alerts: alerts.ServiceClient
    public readonly contexts: contexts.ServiceClient
    public readonly deployments: deployments.ServiceClient
    public readonly files: files.ServiceClient
    public readonly projects: projects.ServiceClient
    public readonly settings: settings.ServiceClient
    public readonly snapshots: snapshots.ServiceClient
    public readonly tests: tests.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.alerts = new alerts.ServiceClient(base)
        this.contexts = new contexts.ServiceClient(base)
        this.deployments = new deployments.ServiceClient(base)
        this.files = new files.ServiceClient(base)
        this.projects = new projects.ServiceClient(base)
        this.settings = new settings.ServiceClient(base)
        this.snapshots = new snapshots.ServiceClient(base)
        this.tests = new tests.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_alerts_create_create } from "~backend/alerts/create";
import { deleteRule as api_alerts_delete_deleteRule } from "~backend/alerts/delete";
import { list as api_alerts_list_list } from "~backend/alerts/list";
import { toggle as api_alerts_toggle_toggle } from "~backend/alerts/toggle";

export namespace alerts {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteRule = this.deleteRule.bind(this)
            this.list = this.list.bind(this)
            this.toggle = this.toggle.bind(this)
        }

        public async create(params: RequestType<typeof api_alerts_create_create>): Promise<ResponseType<typeof api_alerts_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/alerts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_alerts_create_create>
        }

        public async deleteRule(params: { id: number }): Promise<ResponseType<typeof api_alerts_delete_deleteRule>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/alerts/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_alerts_delete_deleteRule>
        }

        /**
         * Retrieves all alert rules for a project.
         */
        public async list(params: { project_id: number }): Promise<ResponseType<typeof api_alerts_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/alerts/${encodeURIComponent(params.project_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_alerts_list_list>
        }

        /**
         * Toggles an alert rule on or off.
         */
        public async toggle(params: RequestType<typeof api_alerts_toggle_toggle>): Promise<ResponseType<typeof api_alerts_toggle_toggle>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                enabled: params.enabled,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/alerts/${encodeURIComponent(params.id)}/toggle`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_alerts_toggle_toggle>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getCurrent as api_contexts_get_current_getCurrent } from "~backend/contexts/get_current";
import { list as api_contexts_list_list } from "~backend/contexts/list";
import { restore as api_contexts_restore_restore } from "~backend/contexts/restore";
import { save as api_contexts_save_save } from "~backend/contexts/save";

export namespace contexts {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getCurrent = this.getCurrent.bind(this)
            this.list = this.list.bind(this)
            this.restore = this.restore.bind(this)
            this.save = this.save.bind(this)
        }

        /**
         * Retrieves the current context snapshot for a project.
         */
        public async getCurrent(params: { project_id: number }): Promise<ResponseType<typeof api_contexts_get_current_getCurrent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contexts/${encodeURIComponent(params.project_id)}/current`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contexts_get_current_getCurrent>
        }

        /**
         * Retrieves all context snapshots for a project.
         */
        public async list(params: { project_id: number }): Promise<ResponseType<typeof api_contexts_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contexts/${encodeURIComponent(params.project_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contexts_list_list>
        }

        public async restore(params: { id: number }): Promise<ResponseType<typeof api_contexts_restore_restore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contexts/${encodeURIComponent(params.id)}/restore`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contexts_restore_restore>
        }

        /**
         * Saves a new context snapshot and marks it as current.
         */
        public async save(params: RequestType<typeof api_contexts_save_save>): Promise<ResponseType<typeof api_contexts_save_save>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contexts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contexts_save_save>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    compare as api_deployments_compare_compare,
    listComparisons as api_deployments_compare_listComparisons
} from "~backend/deployments/compare";
import {
    getCoverage as api_deployments_coverage_getCoverage,
    getCoverageTrend as api_deployments_coverage_getCoverageTrend,
    recordCoverage as api_deployments_coverage_recordCoverage
} from "~backend/deployments/coverage";
import {
    addDependency as api_deployments_dependencies_addDependency,
    getDependencyGraph as api_deployments_dependencies_getDependencyGraph,
    listDependencies as api_deployments_dependencies_listDependencies,
    removeDependency as api_deployments_dependencies_removeDependency
} from "~backend/deployments/dependencies";
import { deploy as api_deployments_deploy_deploy } from "~backend/deployments/deploy";
import {
    createEnvironment as api_deployments_environments_createEnvironment,
    listEnvironments as api_deployments_environments_listEnvironments,
    updateEnvironment as api_deployments_environments_updateEnvironment
} from "~backend/deployments/environments";
import {
    createIncident as api_deployments_incidents_createIncident,
    getIncidentStats as api_deployments_incidents_getIncidentStats,
    listIncidents as api_deployments_incidents_listIncidents,
    updateIncident as api_deployments_incidents_updateIncident
} from "~backend/deployments/incidents";
import { logs as api_deployments_logs_logs } from "~backend/deployments/logs";
import { rollback as api_deployments_rollback_rollback } from "~backend/deployments/rollback";
import { status as api_deployments_status_status } from "~backend/deployments/status";

export namespace deployments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addDependency = this.addDependency.bind(this)
            this.compare = this.compare.bind(this)
            this.createEnvironment = this.createEnvironment.bind(this)
            this.createIncident = this.createIncident.bind(this)
            this.deploy = this.deploy.bind(this)
            this.getCoverage = this.getCoverage.bind(this)
            this.getCoverageTrend = this.getCoverageTrend.bind(this)
            this.getDependencyGraph = this.getDependencyGraph.bind(this)
            this.getIncidentStats = this.getIncidentStats.bind(this)
            this.listComparisons = this.listComparisons.bind(this)
            this.listDependencies = this.listDependencies.bind(this)
            this.listEnvironments = this.listEnvironments.bind(this)
            this.listIncidents = this.listIncidents.bind(this)
            this.logs = this.logs.bind(this)
            this.recordCoverage = this.recordCoverage.bind(this)
            this.removeDependency = this.removeDependency.bind(this)
            this.rollback = this.rollback.bind(this)
            this.status = this.status.bind(this)
            this.updateEnvironment = this.updateEnvironment.bind(this)
            this.updateIncident = this.updateIncident.bind(this)
        }

        public async addDependency(params: RequestType<typeof api_deployments_dependencies_addDependency>): Promise<ResponseType<typeof api_deployments_dependencies_addDependency>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dependencies`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_dependencies_addDependency>
        }

        public async compare(params: RequestType<typeof api_deployments_compare_compare>): Promise<ResponseType<typeof api_deployments_compare_compare>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/compare`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_compare_compare>
        }

        public async createEnvironment(params: RequestType<typeof api_deployments_environments_createEnvironment>): Promise<ResponseType<typeof api_deployments_environments_createEnvironment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/environments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_environments_createEnvironment>
        }

        public async createIncident(params: RequestType<typeof api_deployments_incidents_createIncident>): Promise<ResponseType<typeof api_deployments_incidents_createIncident>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_incidents_createIncident>
        }

        public async deploy(params: RequestType<typeof api_deployments_deploy_deploy>): Promise<ResponseType<typeof api_deployments_deploy_deploy>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/deploy`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_deploy_deploy>
        }

        public async getCoverage(params: RequestType<typeof api_deployments_coverage_getCoverage>): Promise<ResponseType<typeof api_deployments_coverage_getCoverage>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coverage/${encodeURIComponent(params.projectId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_coverage_getCoverage>
        }

        public async getCoverageTrend(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_coverage_getCoverageTrend>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coverage/${encodeURIComponent(params.projectId)}/trend`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_coverage_getCoverageTrend>
        }

        public async getDependencyGraph(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_dependencies_getDependencyGraph>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dependencies/${encodeURIComponent(params.projectId)}/graph`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_dependencies_getDependencyGraph>
        }

        public async getIncidentStats(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_incidents_getIncidentStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents/${encodeURIComponent(params.projectId)}/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_incidents_getIncidentStats>
        }

        public async listComparisons(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_compare_listComparisons>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/${encodeURIComponent(params.projectId)}/comparisons`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_compare_listComparisons>
        }

        public async listDependencies(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_dependencies_listDependencies>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/dependencies/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_dependencies_listDependencies>
        }

        public async listEnvironments(params: { projectId: number }): Promise<ResponseType<typeof api_deployments_environments_listEnvironments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/environments/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_environments_listEnvironments>
        }

        public async listIncidents(params: RequestType<typeof api_deployments_incidents_listIncidents>): Promise<ResponseType<typeof api_deployments_incidents_listIncidents>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                status: params.status === undefined ? undefined : String(params.status),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents/${encodeURIComponent(params.projectId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_incidents_listIncidents>
        }

        public async logs(params: RequestType<typeof api_deployments_logs_logs>): Promise<ResponseType<typeof api_deployments_logs_logs>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                level:        params.level,
                "time_range": params["time_range"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/logs/${encodeURIComponent(params.project_id)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_logs_logs>
        }

        public async recordCoverage(params: RequestType<typeof api_deployments_coverage_recordCoverage>): Promise<ResponseType<typeof api_deployments_coverage_recordCoverage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coverage`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_coverage_recordCoverage>
        }

        public async removeDependency(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/dependencies/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async rollback(params: RequestType<typeof api_deployments_rollback_rollback>): Promise<ResponseType<typeof api_deployments_rollback_rollback>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "deployment_id": params["deployment_id"],
                reason:          params.reason,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/${encodeURIComponent(params.id)}/rollback`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_rollback_rollback>
        }

        public async status(params: { id: number }): Promise<ResponseType<typeof api_deployments_status_status>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployments/${encodeURIComponent(params.id)}/status`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_status_status>
        }

        public async updateEnvironment(params: RequestType<typeof api_deployments_environments_updateEnvironment>): Promise<ResponseType<typeof api_deployments_environments_updateEnvironment>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                config:      params.config,
                "is_active": params["is_active"],
                url:         params.url,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/environments/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_environments_updateEnvironment>
        }

        public async updateIncident(params: RequestType<typeof api_deployments_incidents_updateIncident>): Promise<ResponseType<typeof api_deployments_incidents_updateIncident>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                status:      params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/incidents/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployments_incidents_updateIncident>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_files_list_list } from "~backend/files/list";
import { record as api_files_record_record } from "~backend/files/record";

export namespace files {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
            this.record = this.record.bind(this)
        }

        /**
         * Retrieves file move history for a project.
         */
        public async list(params: { project_id: number }): Promise<ResponseType<typeof api_files_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.project_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_list_list>
        }

        /**
         * Records a file move operation.
         */
        public async record(params: RequestType<typeof api_files_record_record>): Promise<ResponseType<typeof api_files_record_record>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/moves`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_record_record>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_projects_create_create } from "~backend/projects/create";
import { deleteProject as api_projects_delete_deleteProject } from "~backend/projects/delete";
import { get as api_projects_get_get } from "~backend/projects/get";
import { list as api_projects_list_list } from "~backend/projects/list";
import { metricsStream as api_projects_metrics_metricsStream } from "~backend/projects/metrics";
import { update as api_projects_update_update } from "~backend/projects/update";

export namespace projects {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteProject = this.deleteProject.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.metricsStream = this.metricsStream.bind(this)
            this.update = this.update.bind(this)
        }

        public async create(params: RequestType<typeof api_projects_create_create>): Promise<ResponseType<typeof api_projects_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_create_create>
        }

        public async deleteProject(params: { id: number }): Promise<ResponseType<typeof api_projects_delete_deleteProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_delete_deleteProject>
        }

        /**
         * Retrieves a single project by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_projects_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_get_get>
        }

        /**
         * Retrieves all projects, ordered by last activity.
         */
        public async list(): Promise<ResponseType<typeof api_projects_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_list_list>
        }

        public async metricsStream(params: RequestType<typeof api_projects_metrics_metricsStream>): Promise<StreamIn<StreamResponse<typeof api_projects_metrics_metricsStream>>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "interval_ms": params["interval_ms"] === undefined ? undefined : String(params["interval_ms"]),
            })

            return await this.baseClient.createStreamIn(`/projects/${encodeURIComponent(params.project_id)}/metrics/stream`, {query})
        }

        /**
         * Updates project metadata.
         */
        public async update(params: RequestType<typeof api_projects_update_update>): Promise<ResponseType<typeof api_projects_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:    params.description,
                "health_score": params["health_score"],
                metrics:        params.metrics,
                name:           params.name,
                status:         params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { get as api_settings_get_get } from "~backend/settings/get";
import { update as api_settings_update_update } from "~backend/settings/update";

export namespace settings {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Retrieves user preferences.
         */
        public async get(): Promise<ResponseType<typeof api_settings_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_get_get>
        }

        /**
         * Updates user preferences.
         */
        public async update(params: RequestType<typeof api_settings_update_update>): Promise<ResponseType<typeof api_settings_update_update>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/settings`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_settings_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { del as api_snapshots_delete_del } from "~backend/snapshots/delete";
import { list as api_snapshots_list_list } from "~backend/snapshots/list";
import { save as api_snapshots_save_save } from "~backend/snapshots/save";

export namespace snapshots {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.del = this.del.bind(this)
            this.list = this.list.bind(this)
            this.save = this.save.bind(this)
        }

        public async del(params: { id: number }): Promise<ResponseType<typeof api_snapshots_delete_del>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/snapshots/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_snapshots_delete_del>
        }

        public async list(): Promise<ResponseType<typeof api_snapshots_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/snapshots`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_snapshots_list_list>
        }

        public async save(params: RequestType<typeof api_snapshots_save_save>): Promise<ResponseType<typeof api_snapshots_save_save>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/snapshots`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_snapshots_save_save>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { batchRun as api_tests_batch_run_batchRun } from "~backend/tests/batch_run";
import { create as api_tests_create_create } from "~backend/tests/create";
import { deleteTest as api_tests_delete_deleteTest } from "~backend/tests/delete";
import { list as api_tests_list_list } from "~backend/tests/list";
import { run as api_tests_run_run } from "~backend/tests/run";

export namespace tests {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.batchRun = this.batchRun.bind(this)
            this.create = this.create.bind(this)
            this.deleteTest = this.deleteTest.bind(this)
            this.list = this.list.bind(this)
            this.run = this.run.bind(this)
        }

        public async batchRun(params: RequestType<typeof api_tests_batch_run_batchRun>): Promise<ResponseType<typeof api_tests_batch_run_batchRun>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tests/batch-run`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tests_batch_run_batchRun>
        }

        public async create(params: RequestType<typeof api_tests_create_create>): Promise<ResponseType<typeof api_tests_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tests`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tests_create_create>
        }

        public async deleteTest(params: { id: number }): Promise<ResponseType<typeof api_tests_delete_deleteTest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tests/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tests_delete_deleteTest>
        }

        /**
         * Retrieves all test cases for a project.
         */
        public async list(params: { project_id: number }): Promise<ResponseType<typeof api_tests_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tests/${encodeURIComponent(params.project_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tests_list_list>
        }

        /**
         * Updates test results after running a test case.
         */
        public async run(params: RequestType<typeof api_tests_run_run>): Promise<ResponseType<typeof api_tests_run_run>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "actual_output": params["actual_output"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/tests/${encodeURIComponent(params.id)}/run`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_tests_run_run>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
